### PR TITLE
Update yes.html

### PR DESCRIPTION
**Pull request by Peter-A-O**

### CODE REVIEW

**Comment by OlieWu** [comment]
You can use my code, but please make changes on your own and do not try to modify the main branch. Thank you :)

**Comment by Peter-A-O** [comment]
Hey Olie

I think I am doing the right thing by not modifying the main branch, but I am not quite sure. I am totally new to this, so I not doing everything with confidence. I have managed to change the index, but when I pres on the "yes" button on the final website, it leads my directly to the yes.html with a message that says "Cannot retrieve at this moment". Do you know what to do?

thank you again

**Comment by OlieWu** [comment]
No worries, if it says that, it could be a couple issues. 
1) Did you rename the html file?
2) Did you modify the jsx?
** the routing is a little sus in all honesty, so it should be pretty simple to debug **

**Comment by Peter-A-O** [comment]
Do I need to modify the jsx and what is it? Now the site is working a little bit, now the now button does not switch when I click on it and when I press yes, the animated cat does not come? 
here is the link https://peter-a-o.github.io/Cecilie/

**Pull request closed without merging**
